### ISSUE TITLE
Caching the list of servers

### ISSUE THREAD

**Issue by stefanct** [jundymek/free-proxy#2]
The `get()` method is convenient to retrieve individual proxies but since it retrieves the whole list on every invocation it is rather slow and puts a high strain on the sslproxies site unnecessarily.

A better way would be to store the returned list within the class instance and remove individual proxies from the list till it is empty, and only then fetch further proxies (or maybe even have a setting to reuse the old list and rotate through them that way).

What do you think?

**Comment by stefanct** [comment]
Also, there is https://github.com/JaredLGillespie/proxyscrape which seems to be more complete. Maybe you want to join efforts...?

**Comment by jundymek** [comment]
Feel free to write some code and make PR ;) Regarding to proxyscrape I don't think it is a good idea. Free-proxy should by as simple as possible in my opinion.
