### ISSUE TITLE
I think the code is wrong

### ISSUE THREAD

**Issue by xTararAisx** [jundymek/free-proxy#25]
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from free_proxy import FreeProxy
ModuleNotFoundError: No module named 'free_proxy'

**Comment by vol1ura** [comment]
You are right, there is need `fp.fp` instead of `free_proxy`. Actual tests is placed in `test_proxy.py`.

**Comment by jundymek** [comment]
Yes - you were right. I removed the unused `text.py` file. Thanks for your contribution.
