### ISSUE TITLE
Setting https=True gives error

### ISSUE THREAD

**Issue by OffApparition** [jundymek/free-proxy#33]
When I try to get https proxies using
```
from fp.fp import FreeProxy
proxy = FreeProxy(https=True).get()
```

I get the following error
`Exception has occurred: ValueError
check_hostname requires server_hostname`

Setting https to False or completely omitting the parameter works fine. Other parameters also work as intended but I just can't get the https parameter to work.
Am I missing something?

**Comment by MaximKabaev** [comment]
Having the same issue here. This parameter is the only one that gives such error

**Comment by OffApparition** [comment]
I figured out the problem is in the `__check_if_proxy_is_working(self, proxies)` function. When the function is trying to open the google.com URL to check whether the proxy is working or not, it passes the proxy with `https` prefix but there's a bug in the urllib package where the proxy IP's have to actually be passed with the `http` prefix instead.
To fix this problem I just made a new proxy list that consists of the original proxy list but with `http` instead of `https` in the IP; the format is still the same ` proxies = {'https': 'http://127.0.0.1:8888'} ` but as you can see the IP has no `https` prefix. It's still doing a https connection though.

**Comment by jundymek** [comment]
@OffApparition @MaximKabaev - thanks for the feedback. Look at this pr: https://github.com/jundymek/free-proxy/pull/34. I hope it solves the problem with https parameter. I also fixed an additional loop when no working proxy is found. Please - check it in your free time. Thanks a lot for your help.
