### ISSUE TITLE
Suggestion: make test site customable?

### ISSUE THREAD

**Issue by palxex** [jundymek/free-proxy#35]
Sometimes we may want to use other website than google.com for testing. How about keep google.com as default, and add a option for users to customize it?

**Comment by jundymek** [comment]
Thanks, @palxex for the idea.
Anyone else wants this type of feature? I am afraid that it is not a safe option. Somebody can use it with wrong intentions and generate additional traffic on selected websites. 🤔

**Comment by Zapzatron** [comment]
Yes, I do. 
You can write the following: 
The author of this repository is not responsible for any consequences, damages or losses arising from the use or misuse of this repository or content. Users are solely responsible for their actions and any consequences that may follow.

**Comment by hokwanhung** [comment]
Same, that would actually be very useful.

**Comment by jundymek** [comment]
@palxex @Zapzatron @hokwanhung . I'll implement this in the next release.

**Comment by hokwanhung** [comment]
@jundymek Many thanks! Let me know if I could be of any help.

**Comment by jundymek** [comment]
@palxex @Zapzatron @hokwanhung - The test site is now customizable in v1.1.3. Many thanks to @katarzynaheller for the contributions! 🙌
